//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EwoQ.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class acciones_inmediatas
    {
        public long id { get; set; }
        public Nullable<long> codigo_ewo { get; set; }
        public string accion { get; set; }
        public string codigo_responsable { get; set; }
        public Nullable<System.DateTime> fecha_compromiso { get; set; }
        public Nullable<int> evidencia_efectividad { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual ewo ewo { get; set; }
    }
}
