//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EwoQ.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EwoQEntities : DbContext
    {
        public EwoQEntities()
            : base("name=EwoQEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<acciones_inmediatas> acciones_inmediatas { get; set; }
        public virtual DbSet<areas_productivas> areas_productivas { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<equipo_trabajo> equipo_trabajo { get; set; }
        public virtual DbSet<ewo> ewo { get; set; }
        public virtual DbSet<fiveg_resultados> fiveg_resultados { get; set; }
        public virtual DbSet<lineas> lineas { get; set; }
        public virtual DbSet<plantas> plantas { get; set; }
        public virtual DbSet<porque_porque> porque_porque { get; set; }
        public virtual DbSet<preguntas_4m> preguntas_4m { get; set; }
        public virtual DbSet<productos> productos { get; set; }
        public virtual DbSet<respuestas4m> respuestas4m { get; set; }
        public virtual DbSet<revisiones> revisiones { get; set; }
        public virtual DbSet<tipos> tipos { get; set; }
        public virtual DbSet<tipos_data> tipos_data { get; set; }
        public virtual DbSet<zero_ewo> zero_ewo { get; set; }
        public virtual DbSet<zero_questions> zero_questions { get; set; }
        public virtual DbSet<zero_responses> zero_responses { get; set; }
        public virtual DbSet<plan_accion> plan_accion { get; set; }
        public virtual DbSet<excepciones> excepciones { get; set; }
        public virtual DbSet<disposiciones> disposiciones { get; set; }
    }
}
