//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EwoQ.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class disposiciones
    {
        public long id { get; set; }
        public Nullable<long> codigo_ewo { get; set; }
        public Nullable<long> codigo_disposicion { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<long> codigo_unidad_medida { get; set; }
    
        public virtual ewo ewo { get; set; }
        public virtual tipos_data tipos_data { get; set; }
        public virtual tipos_data tipos_data1 { get; set; }
    }
}
