//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EwoQ.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class disposiciones
    {
        public long id { get; set; }
        public Nullable<long> codigo_ewo { get; set; }
        public Nullable<long> codigo_disposicion { get; set; }
        public Nullable<int> cantidad { get; set; }
        public Nullable<long> codigo_unidad_medida { get; set; }
    
        public virtual ewo ewo { get; set; }
        public virtual tipos_data tipos_data { get; set; }
        public virtual tipos_data tipos_data1 { get; set; }
    }
}
