//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EwoQ.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class fiveg_resultados
    {
        public long id { get; set; }
        public Nullable<long> codigo_ewo { get; set; }
        public Nullable<long> codigo_5fv_opcion { get; set; }
        public string condicion { get; set; }
        public string condicion_ideal { get; set; }
        public string checkk { get; set; }
        public string como { get; set; }
        public Nullable<bool> ok { get; set; }
    
        public virtual ewo ewo { get; set; }
    }
}
