//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EwoQ.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class fiveg_resultados
    {
        public long id { get; set; }
        public Nullable<long> codigo_ewo { get; set; }
        public Nullable<long> codigo_5fv_opcion { get; set; }
        public string condicion { get; set; }
        public string condicion_ideal { get; set; }
        public string checkk { get; set; }
        public string como { get; set; }
        public Nullable<bool> ok { get; set; }
    
        public virtual ewo ewo { get; set; }
    }
}
