//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EwoQ.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class plan_accion
    {
        public long id { get; set; }
        public Nullable<long> codigo_ewo { get; set; }
        public string codigo_tipo { get; set; }
        public string contramedida { get; set; }
        public Nullable<bool> requiere_capex { get; set; }
        public Nullable<int> antes { get; set; }
        public Nullable<int> despues { get; set; }
        public Nullable<bool> pokayoke { get; set; }
        public string codigo_responsable { get; set; }
        public Nullable<long> codigo_area { get; set; }
        public Nullable<System.DateTime> fecha_compromiso { get; set; }
    
        public virtual areas_productivas areas_productivas { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual ewo ewo { get; set; }
    }
}
