//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EwoQ.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class porque_porque
    {
        public long id { get; set; }
        public Nullable<long> codigo_ewo { get; set; }
        public string porque1 { get; set; }
        public string porque2 { get; set; }
        public string porque3 { get; set; }
        public string porque4 { get; set; }
        public string porque5 { get; set; }
        public string contramedidas { get; set; }
    
        public virtual ewo ewo { get; set; }
    }
}
