//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EwoQ.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class porque_porque
    {
        public long id { get; set; }
        public Nullable<long> codigo_ewo { get; set; }
        public string porque1 { get; set; }
        public string porque2 { get; set; }
        public string porque3 { get; set; }
        public string porque4 { get; set; }
        public string porque5 { get; set; }
        public string contramedidas { get; set; }
    
        public virtual ewo ewo { get; set; }
    }
}
