//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EwoQ.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class respuestas4m
    {
        public long id { get; set; }
        public Nullable<long> codigo_pregunta { get; set; }
        public Nullable<long> codigo_ewo { get; set; }
        public string verificado { get; set; }
    
        public virtual ewo ewo { get; set; }
        public virtual preguntas_4m preguntas_4m { get; set; }
    }
}
