//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EwoQ.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class zero_ewo
    {
        public long id { get; set; }
        public Nullable<long> codigo_response { get; set; }
        public Nullable<long> codigo_ewo { get; set; }
        public Nullable<int> before { get; set; }
        public Nullable<int> after { get; set; }
    
        public virtual ewo ewo { get; set; }
        public virtual zero_responses zero_responses { get; set; }
    }
}
