//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EwoQ.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class zero_responses
    {
        public long id { get; set; }
        public Nullable<long> codigo_pregunta { get; set; }
        public string respuesta { get; set; }
        public Nullable<int> puntaje { get; set; }
    
        public virtual zero_questions zero_questions { get; set; }
    }
}
