//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EwoQ.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class zero_ewo
    {
        public long id { get; set; }
        public Nullable<long> codigo_response { get; set; }
        public Nullable<long> codigo_ewo { get; set; }
        public Nullable<int> before { get; set; }
        public Nullable<int> after { get; set; }
    }
}
