//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EwoQ.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class zero_questions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public zero_questions()
        {
            this.zero_responses = new HashSet<zero_responses>();
        }
    
        public long id { get; set; }
        public Nullable<long> codigo_ewo { get; set; }
        public Nullable<long> codigo_tipom { get; set; }
        public string pregunta { get; set; }
    
        public virtual ewo ewo { get; set; }
        public virtual tipos_data tipos_data { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<zero_responses> zero_responses { get; set; }
    }
}
